

export const POST_REQUEST_PENDING = "POST_REQUEST_PENDING"
export const POST_REQUEST_FULFILLED = "POST_REQUEST_FULFILLED"
export const POST_REQUEST_FAILED = "POST_REQUEST_FAILED"
export const SET_SORT = "SET_SORT"





